# Generated by Django 5.1.3 on 2024-11-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='عنوان')),
                ('health_condition', models.TextField(verbose_name='الحالة الصحية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
    ]
