# Generated by Django 5.1.3 on 2024-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='health_condition',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='are_you_retired',
            field=models.BooleanField(default=False, verbose_name='Are You Retired?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Social Security Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Membership Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='membership_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Membership Type'),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='patient',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Staff Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='staff_signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='Staff Signature'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
    ]
