# Generated by Django 5.1.3 on 2024-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_options_remove_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'مريض', 'verbose_name_plural': 'المرضى'},
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='الحساسية'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='فصيلة الدم'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, verbose_name='الأدوية الحالية'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='التشخيص'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_results',
            field=models.FileField(blank=True, help_text='يمكنك تحميل ملفات PDF أو صور لنتائج التحاليل', upload_to='lab_results/%Y/%m/', verbose_name='نتائج التحاليل'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='التاريخ الطبي'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_reports',
            field=models.FileField(blank=True, help_text='يمكنك تحميل ملفات PDF أو صور للتقارير الطبية', upload_to='medical_reports/%Y/%m/', verbose_name='التقارير الطبية'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.FileField(blank=True, help_text='يمكنك تحميل ملفات PDF أو صور للوصفات الطبية', upload_to='prescriptions/%Y/%m/', verbose_name='الوصفات الطبية'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='are_you_retired',
            field=models.BooleanField(default=False, verbose_name='هل أنت متقاعد؟'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم شخص للاتصال به في حالات الطوارئ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف الطوارئ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='صلة القرابة'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم العضوية'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='membership_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع العضوية'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الموظف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='staff_signature',
            field=models.CharField(blank=True, max_length=100, verbose_name='توقيع الموظف'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل'), ('other', 'آخر')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
